language: python
python:
  - 2.7
  - 3.6
env:
  - DJANGO=1.10.8 DB=sqlite
  - DJANGO=1.11.13 DB=sqlite
  - DJANGO=2.0.6 DB=sqlite
matrix:
  exclude:
  - python: 2.7
      env: DJANGO=1.10.8 DB=sqlite
  - python: 2.7
      env: DJANGO=1.11.13 DB=sqlite
install:
  - pip install -q Django==$DJANGO
  - pip install coveralls coverage django-discover-runner
script:
  - coverage run --rcfile=.coveragerc setup.py test
after_success:
  - coveralls