language: python
python:
  - 3.6
env:
  global:
    - DB=sqlite
  matrix:
    - DJANGO='>=2.2,<3'
    - DJANGO='>=2.1,<2.2'
    - DJANGO='>=2.0,<2.1'
    - DJANGO='>=1.11,<1.12'

install:
  - pip install -q django$DJANGO
  - pip install coveralls coverage django-discover-runner
script:
  - coverage run --rcfile=.coveragerc setup.py test
after_success:
  - coveralls