# Generated by Django 2.2.7 on 2019-11-22 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yandex_money', '0006_auto_20191122_0321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='fail_url',
            field=models.URLField(verbose_name='URL неуспешной оплаты'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='scid',
            field=models.PositiveIntegerField(verbose_name='Номер витрины'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='shop_id',
            field=models.PositiveIntegerField(verbose_name='ID магазина'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='success_url',
            field=models.URLField(verbose_name='URL успешной оплаты'),
        ),
    ]
